layout_spectrum: 1
color:
  saturation: 0.5721588
  brandStrength: 0.8431382
  lightness: 0.03291186
  brandColors:
    - '#000000'
    - '#649073'
    - '#005B86'
    - '#E2E9ED'
    - '#6EA4D4'
  rhythmicContrast: 0.8683508
typography_spectrum: 0.6703204
name: Testhpm
